Add WinGet Releaser
federico-terzi/espanso pull request #1387
Opened 2022-09-23 21:43 UTC by russellbanks

This pull request adds a workflow that automatically publishes espanso to WinGet every release. *Please do not merge this pull request without reading the below and making the required changes* :)

- `token: ${{ secrets.WINGET_TOKEN }}`

This is the bit that will require action from the person whose account will be used for the pull requests (a member of the espanso GitHub organisation). This is a GitHub token with which the action will authenticate with GitHub and create a pull request on the [winget-pkgs](https://github.com/microsoft/winget-pkgs) repository.

To do this, you will need to:

1. Create a Personal Access Token (PAT) with `public_repo` scope.

![image](https://user-images.githubusercontent.com/74878137/192060610-f5e3f925-bc6d-4dab-98a8-4a29e82449c5.png)

2. Create a repository secret containing the token. **Super important: call this token: `WINGET_TOKEN`**.
See [using encrypted secrets in a workflow](https://docs.github.com/en/actions/security-guides/encrypted-secrets#using-encrypted-secrets-in-a-workflow) for more details.

</br>

**Finally, a fork of [winget-pkgs](https://github.com/microsoft/winget-pkgs) needs to be created under the espanso organisation. Please do not delete the fork after a pull request has been merged as the action will use that fork for making a branch and merging it with the upstream [winget-pkgs](https://github.com/microsoft/winget-pkgs) repository on every espanso release.**

If you would like to read about this action further, the source code and documentation are [here](https://github.com/vedantmgoyal2009/winget-releaser).

Requesting review from @vedantmgoyal2009

2022-09-24 13:05 UTC, vedantmgoyal2009 requested changes

2022-09-24 13:05 UTC, vedantmgoyal2009 commented on .github/workflows/release.yml
> +    needs: [ windows ]
```suggestion
  windows-publish-winget:
    if: ${{ github.ref == 'refs/heads/master' }}
    needs: [ windows ]
```

2022-09-25 04:05 UTC, vedantmgoyal2009 commented
/cc @federico-terzi

2022-10-01 07:31 UTC, vedantmgoyal2009 requested changes

2022-10-01 07:31 UTC, vedantmgoyal2009 commented on .github/workflows/release.yml
> +      - uses: vedantmgoyal2009/winget-releaser@latest
```suggestion
      - uses: vedantmgoyal2009/winget-releaser@v1
```

2023-12-12 16:10 UTC, AucaCoyan commented
Hi! interesting! there are a couple of conflicts to resolve. Can you make it? 💘  Thank you!

2023-12-13 07:27 UTC, vedantmgoyal2009 requested changes
@russellbanks please resolve merge conflicts.

2023-12-13 08:48 UTC, federico-terzi commented
Thanks! Before proceeding with this, I'd like to review how the Github Action for the release work :) I'll try to do it soon

Sorry for the late reply!

2024-07-09 13:15 UTC, AucaCoyan commented
Closing by age. We can talk about it whenever you like!

2024-07-09 13:15 UTC, closed without merging